
                <div id="silver-footer">
                    <div id="silver-footer-left">
                        <div id="silver-footer-right">
                            <div class="silver-address-box">
                               DouglasOnline<br />Long Street<br />Cape Town<br />
                            </div>
                            <div class="silver-address-box">
                                Tel: 073-758-4801<br /><a href="mailto:tamelodouglas@gmail.com">Click here to email us</a>
                            </div>
                            <div class="silver-copyright-info">
                                &copy; 2022 DouglasOnline
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </body>

</html>
<?php
ob_end_flush(); 
?>
